
/*creazione delle tabelle*/

DROP SCHEMA IF EXISTS SISTEMADIGALASSIE CASCADE;


CREATE SCHEMA SISTEMADIGALASSIE;

/*------------------------------------------------------------------------------------------------------------*/

/*		TABELLE MODELLO E-R		*/

/*-----------------------------Galaxy------------------------*/
CREATE TABLE SISTEMADIGALASSIE.Galaxy (
	DISTANCE				VARCHAR,
	NAME					VARCHAR		PRIMARY KEY,
	ALTNAME					VARCHAR,
	SPECTRALCLASSIFICATION	VARCHAR,
	REDSHIFT				FLOAT
);

/*-----------------------------Metallicity------------------------*/
CREATE TABLE SISTEMADIGALASSIE.Metallicity(
	VALUEMET	VARCHAR ,
	ERRORM		VARCHAR ,
	GALAXYNAMEMET 	VARCHAR
					REFERENCES SISTEMADIGALASSIE.Galaxy(NAME),
	PRIMARY KEY (VALUEMET, ERRORM, GALAXYNAMEMET)
);

/*-----------------------------Luminosity------------------------*/
CREATE TABLE SISTEMADIGALASSIE.Luminosity(
	LFLAG 		VARCHAR , 
	ABSORPTION	VARCHAR ,
	GALAXYNAMELUM 	VARCHAR
					REFERENCES SISTEMADIGALASSIE.Galaxy(NAME),
	PRIMARY KEY(LFLAG, ABSORPTION)
);

/*-----------------------------Coordinate------------------------*/
CREATE TABLE SISTEMADIGALASSIE.Coordinate(
	RASCH 	VARCHAR	, 
	RASCM	VARCHAR	,
	RASCS	VARCHAR	,
	DECSIGN	VARCHAR	,
	DECMIN	VARCHAR	,
	DECSEC	VARCHAR	,
	DECDEG	VARCHAR	,
	GALAXYNAMECOO 	VARCHAR
					REFERENCES SISTEMADIGALASSIE.Galaxy(NAME),
	PRIMARY KEY (GALAXYNAMECOO)
);

/*-----------------------------HPfluxR------------------------*/
CREATE TABLE SISTEMADIGALASSIE.HPfluxR(
	NAMEHPR			VARCHAR, 
	PIXELR 			VARCHAR,
	VALUER			VARCHAR,
	ERRORR			VARCHAR,
	FLAGULR			VARCHAR,
	GALAXYNAMEHPR 	VARCHAR
					REFERENCES SISTEMADIGALASSIE.Galaxy(NAME),
	PRIMARY KEY(NAMEHPR, PIXELR, GALAXYNAMEHPR)
);

/*-----------------------------HPfluxC------------------------*/
CREATE TABLE SISTEMADIGALASSIE.HPfluxC(
	NAMEHPC			VARCHAR, 
	PIXELC 			VARCHAR,
	VALUEC			VARCHAR,
	ERRORC			VARCHAR,
	FLAGULC			VARCHAR,
	GALAXYNAMEHPC 	VARCHAR
					REFERENCES SISTEMADIGALASSIE.Galaxy(NAME),
	PRIMARY KEY(NAMEHPC, PIXELc, GALAXYNAMEHPC)
);

/*-----------------------------Spitzerflux------------------------*/
CREATE TABLE SISTEMADIGALASSIE.Spitzerflux(
	NAMES			VARCHAR,
	VALUESP			VARCHAR,
	FLAG 			VARCHAR,
	ERRORS			VARCHAR,
	IRS				VARCHAR,
	GALAXYNAMES 	VARCHAR
					REFERENCES SISTEMADIGALASSIE.Galaxy(NAME),
	PRIMARY KEY(NAMES, GALAXYNAMES)
);

/*		TABELLE IMPLEMENTAZIONE SOFTWARE UTENTE		*/

/*-----------------------------User------------------------*/
CREATE TABLE SISTEMADIGALASSIE.User(
	NOME			VARCHAR		NOT NULL,
	COGNOME			VARCHAR		NOT NULL,
	USERID			VARCHAR		NOT NULL,
	PASSWORD		VARCHAR				,
	EMAIL			VARCHAR				,
	AMMINISTRATORE	VARCHAR				,
	PRIMARY KEY (USERID, PASSWORD)
);

INSERT INTO SISTEMADIGALASSIE.User VALUES ('Simone', 'DAniello', 'Simone', 'Daniello', 'emailsimone', 'TRUE' );
INSERT INTO SISTEMADIGALASSIE.User VALUES ('Mauro', 'Filanti', 'Mauro', 'Filanti', 'emailmauro', 'TRUE' );














